### ISSUE TITLE
Instructions on how to apply the affect in your own project?

### ISSUE THREAD

**Issue by poperigby** [2254FB/Godot-2D-Glow#2]
That would be helpful.

**Comment by univeous** [comment]
Player/sprite 's material and WorldEnvironment in the main scene is basically everything about this effect.
Others is about controll or animation or something else.
The player's material sets specific hdr color to part of sprite,and the worldenvironment makes all the hdr color glow.
If it's still unclear you can check [Brackeys Unity 2D GLOW tutorial](https://www.youtube.com/watch?v=WiDVoj5VQ4c).It's for unity but the main idea is same.

**Comment by poperigby** [comment]
Cool. Maybe put that in the README?

**Comment by univeous** [comment]
> Cool. Maybe put that in the README?

Done.
